swagger: "2.0"
info:
  version: "0.0.1"
  title: "emrinfo"
  description: "API to spin up an AWS EMR cluster, to check status, and to terminate."
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "EMR Rest Service"
  license:
    name: "Apache"
host: 18.191.50.79:8080
basePath: /api
schemes:
  - http
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /emr:
    get:
      description: "Returns status of EMR cluster."
      parameters:
        - in: query
          name: cluster_id
          schema:
            type: string
          description: The EMR cluster id
      produces:
        - "application/json"
      responses:
        "200":
          description: "EMR info"
          schema:
            $ref: "#/definitions/EMR"
        "404":
          description: "ID not found"
definitions:
  EMR:
    type: "object"
    required:
      - "model"
    properties:
      model:
        type: "string"
