swagger: '2.0'
info:
  description: |
    API to spin up an AWS EMR cluster, to check status, and to terminate.
    [http://swagger.io](http://swagger.io) or on 
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: AWS Jupyter/EMR Environment
  contact:
    email: isims@iu.edu
host: "localhost:8081"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
tags:
- name: aws-environments
  description: Spin up the environment
- name: notebooks
  description: Query available notebooks
- name: results
  description: Query analytical results
paths:
  /emr:
    post:
      tags:
      - aws-environments
      summary: Create EMR Cluster
      operationId: createEMR
      produces:
      - application/json
      responses:
        200:
          description: successful
          schema:
            type: string
        400:
          description: unsuccessful
    delete:
      tags:
      - aws-environments
      summary: Terminate EMR Cluster
      operationId: deleteEMR
      parameters:
      - name: cluster-id
        in: path
        required: true
        type: string
      responses:
        200:
          description: successful
          schema:
            type: string
        404:
          description: ID not found
    get:
      tags:
      - aws-environments
      summary: Get the status of EMR cluster
      operationId: getStatusEMR
      produces:
      - application/json
      parameters:
      - name: cluster-id
        in: path
        required: true
        type: string
      responses:
        200:
          description: successful
          schema:
            type: string
        404:
          description: ID not found
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Sims-Student/AWS-Environment-Creation/1.0.0
schemes:
 - https
 - http
